# docker-compose file with mysql service
version: '3'
services:
  main-mysql:
    image: mysql
    container_name: main-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/main:/var/lib/mysql
  shadow-mysql:
    image: mysql
    container_name: shadow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shadow
      MYSQL_USER: shadow
      MYSQL_PASSWORD: shadow
    ports:
      - "13306:3306"
    volumes:
      - ./mysql/shadow:/var/lib/mysql