version: "3"
services:
  main-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  shadow-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shadow
      MYSQL_USER: shadow
      MYSQL_PASSWORD: shadow
    ports:
      - "13306:3306"
    volumes:
      - db-shadow:/var/lib/mysql
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    command: yarn dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: "mysql://dev:password@main-mysql:3306/dev"

volumes:
  db:
  db-shadow:
