blank_issues_enabled: false
contact_links:
- name: Feature Request
  url: https://github.com/codelabsab/workflow-manager/discussions/new?category=ideas
  about: Please create a new Discussion in ideas category before making feature request.
