name: Lint check

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Run yarn install
        run: yarn install
      - name: copy .env-example to .env
        run: cp .env-example .env
      - name: Run yarn lint
        run: yarn lint
